spring:
   application:
      name: central-config-server
   cloud:
      config: 
         server:
            git: 
              uri: https://github.com/SaiUpadhyayula/microservices-config-server
              username: 
              password: 
              clone-on-startup: true
               
      
server:
   port: 8888