eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
server:
  port: 8761
spring:
  security:
    user:
      name: eureka
      password: password
      roles:
      - USER