spring:
  datasource:
    url: jdbc:mysql://@localhost:3306/order_service
    username: root
    password: mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: order-service      
server:
  port: 8082
#grpc:
#  server:
#    port: 6566

inventory:
   url: http://localhost:8083

#logging:
#  pattern:
#    console: "%d{yyyy-MM-dd HH:mm:ss} %-5level [%thread] %logger{36} - %msg%n"

#logging:
#  level:
#    root: INFO
#    org:
#      springframework:
#        cloud:
#          openfeign: TRACE
#    feign: TRACE

eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@127.0.0.1:8761/eureka

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include:
        - "*"
  endpoint:
    health:
      show-details: always
resilience4j:
# Circuit Breaker properties
  circuitbreaker:
    instances:
      inventory:
        register-health-indicator: true
        event-consumer-buffer-size: 10
        sliding-window-type: count-based
        sliding-window-size: 5
        failure-rate-threshold: 50
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 3
        automatic-transition-from-open-to-half-open-enabled: true
# Time Limiter propreties
  timelimiter:
    instances:
      inventory:
        timeout-duration: 3s
# Retry properties
  retry:
    instances:
      inventory:
        max-attempts: 3
        wait-duration: 5s
      