spring:
  application:
    name: product-service
  data:
    mongodb:
      uri: mongodb://root:password@localhost:27017/product-service?authSource=admin
server:
  port: 8081
eureka:
  client:
    service-url:
      defaultZone: http://eureka:password@127.0.0.1:8761/eureka
